export interface TraitLayers {
  element: "Fire" | "Earth" | "Air" | "Water";
  modality: "Cardinal" | "Fixed" | "Mutable";
  ruler: string;
  archetype: string;
  themes: string[];
  core: string[];
  shadow: string[];
  conflict: string;
  integration: string;
}

export const SIGN_TRAITS: Record<string, TraitLayers> = {
  Aries: {
    element: "Fire",
    modality: "Cardinal",
    ruler: "Mars",
    archetype: "Pioneer: initiative, courage, raw drive to start.",
    themes: ["first moves and leadership", "impulse vs restraint"],
    core: ["direct", "courageous", "energetic", "protects autonomy"],
    shadow: ["impatient", "argument-prone", "starts then drops"],
    conflict: "You want to lead and move fast; impatience can damage trust.",
    integration: "Clear goals, cool down before fights, finish one thing before the next.",
  },
  Taurus: {
    element: "Earth",
    modality: "Fixed",
    ruler: "Venus",
    archetype: "Builder: stability, senses, loyalty over time.",
    themes: ["security and resources", "comfort vs change"],
    core: ["steady", "patient", "sensual", "loyal when trust exists"],
    shadow: ["stubborn", "possessive", "avoids change"],
    conflict: "You want safety; fear of loss can make you cling or freeze.",
    integration: "Small steps toward change; name fear early.",
  },
  Gemini: {
    element: "Air",
    modality: "Mutable",
    ruler: "Mercury",
    archetype: "Messenger: curiosity, language, ideas, social wiring.",
    themes: ["communication", "variety vs depth"],
    core: ["curious", "adaptable", "witty", "connects people and ideas"],
    shadow: ["scattered", "glib", "avoids deep feeling"],
    conflict: "You need novelty; scattered focus can hurt intimacy.",
    integration: "One anchor project; say feelings plainly, not only jokes.",
  },
  Cancer: {
    element: "Water",
    modality: "Cardinal",
    ruler: "Moon",
    archetype: "Protector: home, attachment, emotional safety.",
    themes: ["belonging", "mood as signal"],
    core: ["nurturing", "perceptive", "loyal to inner circle", "protective"],
    shadow: ["withdraws", "indirect", "clings or tests"],
    conflict: "You want closeness; fear of hurt can make you retreat or confuse others.",
    integration: "Rhythm, named needs, separate past from present.",
  },
  Leo: {
    element: "Fire",
    modality: "Fixed",
    ruler: "Sun",
    archetype: "Heart: visibility, warmth, creative pride.",
    themes: ["recognition", "play vs ego"],
    core: ["warm", "generous", "brave creatively", "loyal"],
    shadow: ["pride", "needs attention", "thin skin to criticism"],
    conflict: "You want loyalty and recognition; pride can block repair.",
    integration: "Share credit; vulnerability after conflict.",
  },
  Virgo: {
    element: "Earth",
    modality: "Mutable",
    ruler: "Mercury",
    archetype: "Analyst: skill, service, refinement, health.",
    themes: ["improvement", "detail vs overwhelm"],
    core: ["discerning", "helpful", "practical", "humble worker"],
    shadow: ["perfectionist", "anxious", "nitpicks"],
    conflict: "You want usefulness; anxiety and critique can drain joy.",
    integration: "Good-enough; worth separate from output.",
  },
  Libra: {
    element: "Air",
    modality: "Cardinal",
    ruler: "Venus",
    archetype: "Diplomat: balance, partnership, fairness.",
    themes: ["harmony", "approval vs truth"],
    core: ["tactful", "fair", "relationship-oriented", "aesthetic"],
    shadow: ["people-pleasing", "indecisive", "resentment hidden"],
    conflict: "You want peace; avoiding conflict can hide truth and self.",
    integration: "Limits, timed decisions, honest disagreement.",
  },
  Scorpio: {
    element: "Water",
    modality: "Fixed",
    ruler: "Mars; Pluto (modern)",
    archetype: "Depth: intensity, loyalty, transformation, trust.",
    themes: ["power and vulnerability", "all-or-nothing bonds"],
    core: ["intense", "loyal", "perceptive", "transforms under pressure"],
    shadow: ["jealous", "controlling", "tests or withdraws"],
    conflict: "You want depth; fear of betrayal can push control or withdrawal.",
    integration: "Direct truth, consent, chosen vulnerability.",
  },
  Sagittarius: {
    element: "Fire",
    modality: "Mutable",
    ruler: "Jupiter",
    archetype: "Seeker: freedom, meaning, honesty, horizons.",
    themes: ["belief and travel", "freedom vs commitment"],
    core: ["optimistic", "honest", "adventurous", "generous"],
    shadow: ["restless", "blunt", "preachy"],
    conflict: "You need freedom and truth; bluntness and restlessness can hurt closeness.",
    integration: "Tact; keep promises; stay through ordinary moments.",
  },
  Capricorn: {
    element: "Earth",
    modality: "Cardinal",
    ruler: "Saturn",
    archetype: "Builder of time: duty, ambition, structure.",
    themes: ["long-term goals", "duty vs warmth"],
    core: ["disciplined", "strategic", "patient", "shows care by doing"],
    shadow: ["cold", "rigid", "workaholic"],
    conflict: "You want mastery; fear can narrow life to duty and distance.",
    integration: "Rest, play, small emotional risks.",
  },
  Aquarius: {
    element: "Air",
    modality: "Fixed",
    ruler: "Saturn; Uranus (modern)",
    archetype: "Reformer: ideas, community, originality.",
    themes: ["ideals", "distance vs intimacy"],
    core: ["independent", "principled", "future-minded", "fair"],
    shadow: ["detached", "contrarian", "avoids feelings"],
    conflict: "You value freedom and truth; distance can block warmth in close ties.",
    integration: "Chosen intimacy; vulnerability on purpose.",
  },
  Pisces: {
    element: "Water",
    modality: "Mutable",
    ruler: "Jupiter; Neptune (modern)",
    archetype: "Mystic: empathy, imagination, merging, compassion.",
    themes: ["boundaries", "escape vs faith"],
    core: ["empathetic", "imaginative", "gentle", "intuitive"],
    shadow: ["escapist", "merged boundaries", "confused"],
    conflict: "You want connection; weak boundaries can overwhelm or erase self.",
    integration: "Clear limits; compassion with discernment.",
  },
};
